--RESTORE DATABASE QUERY

RESTORE FILELISTONLY
FROM DISK = '/var/opt/mssql/data/JARVISPOSVALLEDULCE.bak';
GO

RESTORE DATABASE JARVISPOSVALLEDULCEPRUEBA
FROM DISK = '/var/opt/mssql/data/JARVISPOSVALLEDULCE.bak'
WITH MOVE 'DEVJARVISPOS' TO '/var/opt/mssql/data/JARVISPOSVALLEDULCEPRUEBA.mdf',
     MOVE 'DEVJARVISPOS_log' TO '/var/opt/mssql/data/JARVISPOSVALLEDULCEPRUEBA_log.ldf',
     REPLACE;
GO

SELECT * FROM JARVISPOSVALLEDULCEPRUEBA.INFORMATION_SCHEMA.TABLES